name: digest
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - jupyter_client<7.0.0
  - nb_conda=2.2.1
  - numpy=1.19.2
  - python=3.8.5
  - matplotlib=3.3.1
  - scikit-learn=0.23.1
  - spacy=2.3.5
  - nltk=3.5
  - gensim=3.8.3
  - pip:
    - openai==0.26.5
    - opencv-python==4.7.0.68
    - PyPDF2==3.0.1
    - pytesseract==0.3.10
    - google-api-core==2.11.0
    - google-auth==2.16.1
    - google-cloud-speech==2.17.3
    - googleapis-common-protos==1.58.0
    - beautifulsoup4==4.11.1
    - moviepy==1.0.3
    - pydub==0.25.1
